version: '3.1'
services:
  stats-server:
    build: ./ewm-stats-service
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreWithMe-stats-db
      - DB_USERNAME=root
      - DB_PASSWORD=secret_password
      - SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=exploreWithMe-stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret_password

  ewm-service:
    build: ./ewm-main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/exploreWithMe-main-db
      - DB_USERNAME=root
      - DB_PASSWORD=main_secret_password
      - SERVER_PORT=8080

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6551:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=exploreWithMe-main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=main_secret_password